### ISSUE TITLE
[Android Bootcamp] Project 3: Twitter Client - Ready for Review

### ISSUE THREAD

**Issue by paulinar** [paulinar/chirper#1]
My app is complete, please review! :) /cc @codepathreview @codepath

Comments:
- I spent a lot of time trying to get infinite scroll to work with the new "max_id" method, but resorted to using "page" instead because I couldn't get it. :(
- I didn't have time to implement data persistence (argh!) but I fully intend to do so, even though it won't be a part of this assignment submission.

**Comment by nesquena** [comment]
> I spent a lot of time trying to get infinite scroll to work with the new "max_id" method, but resorted to using "page" instead because I couldn't get it. :(

What was the issue you ran into?

> I didn't have time to implement data persistence (argh!) but I fully intend to do so, even though it won't be a part of this assignment submission.

Next week's project is building on top and extending the twitter client you started this week so it's a great opportunity to add several of the week 3 functionality (like persistence) in addition to the rest of the 4th assignment which we will introduce tomorrow. Full review shortly.

**Comment by paulinar** [comment]
@nesquena 

With max_id, my timeline kept recycling the old tweets instead of fetching new ones -- I think I also had a hard time understanding the usage max_id conceptually, even after reading the Twitter documentation... I'll try to give max_id a shot again and see if I can replicate the error I was getting. At one point, I actually got rate limited from making excessive calls to the Twitter API so I ended up making an separate developer account. (I think it was because I was messing around with infinite scroll and pull-to-refresh so much that I was unintentionally making a ton of API requests).

I also had other questions about this assignment:
- In TwitterClient.java, is there a difference between using getClient().get(..) vs. client.get(..)? Or will both be referring to the same client instance?
- I noticed in your latest commit to android-rest-client-template that you used gradle for activeandroid and deleted the jar from the libs folder. I went ahead and followed suit -- out of curiosity, is it always preferable or "best practice" to use gradle for third-party libraries, as opposed to their jar files?

**Comment by nesquena** [comment]
> At one point, I actually got rate limited from making excessive calls to the Twitter API so I ended up making an separate developer account. 

Yeah you can read about rate limiting here: https://dev.twitter.com/docs/rate-limiting/1.1

> I think I also had a hard time understanding the usage max_id conceptually, even after reading the Twitter documentation

In short, `max_id` is a parameter which dictates the maximum id of the tweet that the next round of results will show. So what you need to do is keep track of the oldest tweet id you currently have in the timeline (by checking the array of tweets) then pass that as the max_id into the next request. Let me know if you have any specific questions.

> In TwitterClient.java, is there a difference between using getClient().get(..) vs. client.get(..)? Or will both be referring to the same client instance?

They are identical, it's the same client instance (client is a singleton, there's only one generally speaking across the whole app).

> I noticed in your latest commit to android-rest-client-template that you used gradle for activeandroid and deleted the jar from the libs folder. I went ahead and followed suit -- out of curiosity, is it always preferable or "best practice" to use gradle for third-party libraries, as opposed to their jar files?

JAR files are a legacy of eclipse and the world before gradle. Generally speaking if you can load using Gradle, it is always preferable. This is because JARs are wasting space in the repo by loading the code for the library, also JARs don't have versions understood by the system and as such dependency conflicts come up a lot, updating JARs is totally manual, etc.

**Comment by codepathreview** [comment]
:+1: Great work! A few notes after checking out the code:
- Good to see you were able to format the timestamp cleanly (consider externalizing to utils class)
- Nice to see you used the `SwipeRefreshLayout` for easy timeline refreshes
- The home timeline does not display a tweet after it has been composed by the user. See the helpful hints guide.
- Consider adding local persistence of tweets by using ActiveAndroid in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/ActiveAndroid-Guide) for more details.
-  Nice touch with the character count being displayed while the user composes a tweet 
- Great effort on the UI to make it more twitter branded

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
